### PR TITLE
Data drop backend set up.

### PR DESCRIPTION
**Pull request by dkorolev**
Hi @sompylasar ,

**Part 1**: Set up the data drop and confirmed it does what it should: Done, PTAL.

**Part 2**: Serve the script itself. In progress.

Thanks,
Dima

CC @mzhurovich for nginx magic. It's on our Hetzner instance now.

### CODE REVIEW

**Comment by znrg** [comment]
cool. I'm standing by to inject JS into www.ctfo.website.

**Comment by dkorolev** [comment]
@znrg : I hosted our script on `https://secure.c5t.io/datadrop/v1/c5t.js`, and the following HTML successfully sends events to us: http://pastebin.com/8YTThQ8J

**Comment by dkorolev** [comment]
To: @mzhurovich
Cc: @sompylasar , @znrg 

Here's the end-to-end sanity check.
1. `$ ssh ubuntu@secure.c5t.io tail -n 0 -f datadrop.txt` and keep it running.
2. Save the above HTML and open it in the browser.
3. See this in the output of the command in p.1:

```
{"log_entry":{"t":1438751257249,"m":"POST","u":"/log","q":[{"key":"CUSTOMER_ACCOUNT","value":"TEST_ACCOUNT_ID"}],"b":"_t=1438751257032&t=event&ec=C5T&ea=Ex&fg=1&cid=14efc419b15da-093d29ae3-2c044c73-15f900-14efc419b17211","f":""}}
{"log_entry":{"t":1438751257588,"m":"GET","u":"/log","q":[{"key":"CUSTOMER_ACCOUNT","value":"TEST_ACCOUNT_ID"},{"key":"_t","value":"1438751257438"},{"key":"cid","value":"14efc41f359273-0374dc5ce-2c044c73-15f900-14efc41f35a160"},{"key":"ea","value":"En"},{"key":"ec","value":"C5T"},{"key":"fg","value":"1"},{"key":"t","value":"event"}],"b":"","f":""}}
{"log_entry":{"t":1438751257591,"m":"GET","u":"/log","q":[{"key":"CUSTOMER_ACCOUNT","value":"TEST_ACCOUNT_ID"},{"key":"_t","value":"1438751257441"},{"key":"cid","value":"14efc41f359273-0374dc5ce-2c044c73-15f900-14efc41f35a160"},{"key":"ea","value":"Fg"},{"key":"ec","value":"C5T"},{"key":"fg","value":"1"},{"key":"t","value":"event"}],"b":"","f":""}}
```

**Comment by znrg** [comment]
@dkorolev: injected into www.ctfo.website. the traffic is starting to flow in. plz check to see if you're getting anything from it.

**Comment by dkorolev** [comment]
@znrg Yes! Can see "Enter" and "Foreground" events after just briefly opening the page.

```
$ ssh ubuntu@secure.c5t.io tail -n 0 -f datadrop.txt

{"log_entry":{"t":1438751702773,"m":"GET","u":"/log","q":[{"key":"CUSTOMER_ACCOUNT","value":"CTFO_WEB_USER"},{"key":"_t","value":"1438751702634"},{"key":"cid","value":"14efc48be67272-0faa3244a-2c044c73-15f900-14efc48be68bd3"},{"key":"ea","value":"En"},{"key":"ec","value":"C5T"},{"key":"fg","value":"1"},{"key":"t","value":"event"}],"b":"","f":""}}

{"log_entry":{"t":1438751703032,"m":"GET","u":"/log","q":[{"key":"CUSTOMER_ACCOUNT","value":"CTFO_WEB_USER"},{"key":"_t","value":"1438751702636"},{"key":"cid","value":"14efc48be67272-0faa3244a-2c044c73-15f900-14efc48be68bd3"},{"key":"ea","value":"Fg"},{"key":"ec","value":"C5T"},{"key":"fg","value":"1"},{"key":"t","value":"event"}],"b":"","f":""}}
```

**Comment by znrg** [comment]
view-source:http://www.ctfo.website/ (Web version):
lines 471 - 501

**Comment by znrg** [comment]
> @znrg Yes! Can see "Enter" and "Foreground" events after just briefly opening the page.

Could this be because @sompylasar is a good engineer? It's possible, right?

**Comment by dkorolev** [comment]
Yes, I would certainly not discount this possibility.

So far, it's the simplest explanation we have, thus my religion forces me to stick with it.

**Comment by znrg** [comment]
> Yes, I would certainly not discount this possibility.
> So far, it's the simplest explanation we have, thus my religion forces me to stick with it.

:)

**Comment by dkorolev** [comment]
@znrg : Extra kudos for separating `WEB` and `MOBILE` events.

**Comment by sompylasar** [comment]
@znrg There's no need to `name` a tracker if you're using a single tracker
instance (using 'create' only once).
And with the latest version of the script, enter/exit and
foreground/background are tracked by default, there's no need to add the
flags.

**Comment by znrg** [comment]
Got it, thx.

**Pull request merged**
